
version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: PMA_HOST # 数据库服务器地址
      PMA_PORT: 3306 # 数据库服务器端口
    restart: always
