
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    volumes:
      - /data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
